In [1]:
import torch
print(torch.__version__)

1.3.1+cpu


In [2]:
torch.set_default_dtype(torch.float64)

In [3]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [4]:
filling = torch.full((2,6), fill_value = 10)
filling

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [5]:
filling = torch.full((2,6),10)
filling

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [6]:
tensor_lik = torch.zeros_like(filling)
tensor_lik

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [7]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [8]:
dia_idx = torch.nonzero(tensor_eye)
dia_idx

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

Note that for spare tensor, we use a small leter for it. example bellow. 

In [9]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.9314, 0.4468, 0.5333],
        [0.4654, 0.6780, 0.3011]])

In [10]:
initial_tensor.fill_(10)  # The fact that we have fill_ make it overwrite what we had before e.g implace function

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [11]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [12]:
initial_tensor  # here you notice that because we did not add the _ after adding 4 above, we see that the initial_tensor was still 10

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [13]:
initial_tensor.add_(8)

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [14]:
initial_tensor   # we can see that adding _ over wrote what was there before 

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [15]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [16]:
new_tensor.sqrt_()

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [17]:
x = torch.linspace(0.1,10,15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [18]:
tensor_chunk = torch.chunk(x,3,0)  # This means spliting x into 3 parts
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [19]:
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [20]:
new_tensor.shape

torch.Size([2, 3])

In [21]:
tensor_unsqueeze = torch.unsqueeze(new_tensor,2)
tensor_unsqueeze

tensor([[[3.8730],
         [3.8730],
         [3.8730]],

        [[3.8730],
         [3.8730],
         [3.8730]]])

In [22]:
tensor_unsqueeze.shape

torch.Size([2, 3, 1])

In [23]:
initial_tensor[1,1] = 4
initial_tensor

tensor([[18., 18., 18.],
        [18.,  4., 18.]])

In [24]:
sorted_tensor , sorted_indices = torch.sort(initial_tensor)
sorted_tensor

tensor([[18., 18., 18.],
        [ 4., 18., 18.]])

In [25]:
sorted_indices

tensor([[0, 1, 2],
        [1, 0, 2]])

In [26]:
rand1 = torch.abs(torch.randn(2,3))
rand2 = torch.abs(torch.randn(2,3))

In [27]:
rand1

tensor([[1.3351, 0.5714, 0.4350],
        [1.7014, 1.0024, 0.7942]])

In [28]:
rand2

tensor([[0.3054, 1.4737, 0.6453],
        [1.6170, 0.0270, 0.5655]])

In [29]:
add1 = rand1 + rand2
add1

tensor([[1.6405, 2.0450, 1.0803],
        [3.3183, 1.0294, 1.3597]])

In [30]:
add2 = torch.add(rand1, rand2)  # this is for elemet wise addition

In [31]:
add2

tensor([[1.6405, 2.0450, 1.0803],
        [3.3183, 1.0294, 1.3597]])

In [32]:
multiplication = torch.mul (rand1, rand2)
multiplication

tensor([[0.4077, 0.8420, 0.2807],
        [2.7510, 0.0271, 0.4491]])

In [33]:
multiplit = torch.Tensor(multiplication)
multiplit

tensor([[0.4077, 0.8420, 0.2807],
        [2.7510, 0.0271, 0.4491]])

In [34]:
tensor_clamp = torch.clamp(multiplit, min = 0.5, max = 1.5)
tensor_clamp

tensor([[0.5000, 0.8420, 0.5000],
        [1.5000, 0.5000, 0.5000]])

In [35]:
torch.cuda.is_available()

False

#### Autograd

In [44]:
tensor1 = torch.Tensor([[1,2,3],[4,5,6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [50]:
tensor2 = torch.Tensor([[7,2,3],[4,8,6]])
tensor2

tensor([[7., 2., 3.],
        [4., 8., 6.]])

In [51]:
tensor1.requires_grad_()  # make it require grad available

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [52]:
print(tensor1.grad)  # since no computation has been done yet, so it would be noe

None


In [53]:
print(tensor1.grad_fn)  # This is adding the function grad to it

None


In [54]:
output = tensor1 * tensor2

In [56]:
output.requires_grad     # This would be true cause at least one of the tensors are true. (tensor 1) 

True

In [60]:
output_mean = (tensor1 * tensor2).mean()
output_mean

tensor(18.6667, grad_fn=<MeanBackward0>)

In [57]:
print(tensor1.grad) # no gradient would still be done casue there is no backward prop yet

None


In [58]:
print(tensor2.grad)  # no gradient would still be done casue there is no backward prop yet

None


In [61]:
output_mean.backward()    # The backward prop has been done now, so we can expect to have gradient

In [62]:
print(tensor1.grad)    # now e have out gradient

tensor([[1.1667, 0.3333, 0.5000],
        [0.6667, 1.3333, 1.0000]])


In [63]:
print(tensor2.grad)  # remember that we didn't put __ for the required grad for thensor 2 ( check above and comfirm) hence, no gradient s calculated for tensor 2

None


In [66]:
tensor1_mul = tensor1 * 3    # you can notice that the multiplication is done backward
tensor1_mul

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)

#### if you don't want any computation to be store i.e, history tracking turned off, you can do as follows

In [71]:
with torch.no_grad():
    new_tensor1 = tensor1 + 6
    
    print('new_tensor = ', new_tensor)
    print('This is the tensor we just created here tensor1 = ', new_tensor.requires_grad)
    print('This was our original tensor1 = ', tensor1.requires_grad)

    
# we can see that the one we just created is false beacuse it was created in the tensor.no_grad block

new_tensor =  tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])
This is the tensor we just created here tensor1 =  False
This was our original tensor1 =  True


In [72]:
reflections = {
  "i am"       : "you are",
  "i was"      : "you were",
  "i"          : "you",
  "i'm"        : "you are",
  "i'd"        : "you would",
  "i've"       : "you have",
  "i'll"       : "you will",
  "my"         : "your",
  "you are"    : "I am",
  "you were"   : "I was",
  "you've"     : "I have",
  "you'll"     : "I will",
  "your"       : "my",
  "yours"      : "mine",
  "you"        : "me",
  "me"         : "you"
}

In [73]:
my_dummy_reflections= {
    "go"     : "gone",
    "hello"    : "hey there"
}

In [74]:
chat = Chat(pairs, my_dummy_reflections)

NameError: name 'Chat' is not defined

In [81]:
from nltk.chat.util import Chat, reflections

In [85]:
pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, How are you today ?",]
    ],
     [
        r"what is your name ?",
        ["My name is Chatty and I'm a chatbot ?",]
    ],
    [
        r"how are you ?",
        ["I'm doing good\nHow about You ?",]
    ],
    [
        r"sorry (.*)",
        ["Its alright","Its OK, never mind",]
    ],
    [
        r"i'm (.*) doing good",
        ["Nice to hear that","Alright :)",]
    ],
    [
        r"hi|hey|hello",
        ["Hello", "Hey there",]
    ],
    [
        r"(.*) age?",
        ["I'm a computer program dude\nSeriously you are asking me this?",]
        
    ],
    [
        r"what (.*) want ?",
        ["Make me an offer I can't refuse",]
        
    ],
    [
        r"(.*) created ?",
        ["Nagesh created me using Python's NLTK library ","top secret ;)",]
    ],
    [
        r"(.*) (location|city) ?",
        ['Chennai, Tamil Nadu',]
    ],
    [
        r"how is weather in (.*)?",
        ["Weather in %1 is awesome like always","Too hot man here in %1","Too cold man here in %1","Never even heard about %1"]
    ],
    [
        r"i work in (.*)?",
        ["%1 is an Amazing company, I have heard about it. But they are in huge loss these days.",]
    ],[
        r"(.*)raining in (.*)",
        ["No rain since last week here in %2","Damn its raining too much here in %2"]
    ],
    [
        r"how (.*) health(.*)",
        ["I'm a computer program, so I'm always healthy ",]
    ],
    [
        r"(.*) (sports|game) ?",
        ["I'm a very big fan of Football",]
    ],
    [
        r"who (.*) sportsperson ?",
        ["Messy","Ronaldo","Roony"]],
    [
        r"who (.*) (moviestar|actor)?",
        ["Brad Pitt"]],
    [
        r"quit",
        ["BBye take care. See you soon :) ","It was nice talking to you. See you soon :)"]],
]
def chatty():
    print("Hi, I'm Chatty and I chat alot ;)\nPlease type lowercase English language to start a conversation. Type quit to leave ") #default message at the start    chat = Chat(pairs, reflections)
    chat = Chat(pairs, reflections)
    chat.converse()
   

In [86]:
 chatty()

Hi, I'm Chatty and I chat alot ;)
Please type lowercase English language to start a conversation. Type quit to leave 
>what is your name?
My name is Chatty and I'm a chatbot ?
>hello
Hello
>hi
Hello
>hii
Hey there
>i need help
None
>please
None


KeyboardInterrupt: 

In [5]:
L = [i for i in range(100)]
L;

In [6]:
while L:
    L.pop()
L

[]